"""empty message

Revision ID: da5b98e64a05
Revises: 4677c0011688
Create Date: 2022-05-31 20:02:05.769043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5b98e64a05'
down_revision = '4677c0011688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram')
    # ### end Alembic commands ###
